### ISSUE TITLE
[Feature request] Add format methods?

### ISSUE THREAD

**Issue by WaldoJeffers** [jbdemonte/vat-siren-siret#1]
Hello,

This is a great & useful lib!
I often need to format SIREN, SIRET or VAT numbers. It's quite easy to do, but I think it would be a great addition to this library, as you often need to format these numbers while displaying them.
```js
vss.formatSIREN('813454717') // 813 454 717
vss.formatSIRET('81345471700014') // 813 454 717 00014
vss.formatVAT('FR42813454717') // FR 42 813 454 717
```

I can create a PR if you're interested, let me know @jbdemonte 😄

**Comment by jbdemonte** [comment]
Hi Waldo,

Sorry for the delay, but yes, if you wand to submit a PR, I'll be pleased because right now, I have to say that, I won't have enough time ...

**Comment by WaldoJeffers** [comment]
Thanks @jbdemonte , here's https://github.com/jbdemonte/vat-siren-siret/pull/2!

**Comment by jbdemonte** [comment]
Thanks,

Could you update the readme, add the jsdoc of your functions and update the package version (minor) ?

**Comment by WaldoJeffers** [comment]
@jbdemonte done in https://github.com/jbdemonte/vat-siren-siret/pull/4 😄 Sorry it took so long :/

**Comment by jbdemonte** [comment]
No problem, thanks :)
